decred/dcrctl

README.md
The major versions of the modules in these examples must be updated as
dcrctl imports new major versions of the packages in the future.
=> docs: Provide example commands for developing with replaces

config.go, httpclient.go
Requires https://github.com/decred/dcrwallet/pull/1867
This diff adds 3 new options to be able to use dcrctl against a wallet that has `authtype=clientcert`
`WalletGRPC` should be set to true in this case and then it will pull the required cert and key from 
the default location (~/.dcrctl/client.pem and ~/.dcrctl/client-key.pem) or use whatever path the user
sets for `ClientCert` and `ClientKey`.  The client.pem needs to also be appended to the dcrwallet
clients.pem file.
=> Add ClientCert and ClientKey for newly required grpc auth

config.go, httpclient.go
This modifies the config parsing for the new `authtype` option to enforce only the two supported types and sets the default to the `userpass` type.
It also enforces that the new `authtype` of `clientcert` requires TLS regardless of the `wallet` flag being set because it is perfectly
acceptable to manually specify a wallet as a target without the wallet flag that tells it to use the default ports.
Finally, it modifies it so that the client cert and key are loaded when the authorization type is `clientcert` regardless of the `wallet` flag for the same reason as above.
=> Cleanup authtype option.

version.go
This clears the `PreRelease` and sets the `BuildMetadata` to `release.local` on the release branch so that anyone building the release branch will end up with version "1.6.0+release.local" indicating it was a local build as opposed to a reproducible release build.
=> [release-v1.6] release: Bump for 1.6.0.

go.mod, go.sum
This is a backport of #22 to the 1.6 release branch.
=> [release-v1.6] deps: Update to latest dcrd/dcrwallet rel modules.

go.mod, go.sum
This is a backport of #24 to the 1.6 release branch.
=> [release-v1.6] deps: Update to latest dcrd rel modules.

README.md
`go.mod` imports `decred.org/dcrwallet/v2`, however the replace commands in `README.md` were attempting to replace `decred.org/dcrwallet` (missing the `/v2` suffix).
=> docs: Add version to dcrwallet replace cmds

version.go
This clears the `PreRelease` and sets the `BuildMetadata` to `release.local` on the release branch so that anyone building the release branch will end up with version "1.7.0+release.local" indicating it was a local build as opposed to a reproducible release build.
=> [release-v1.7] release: Bump for 1.7.0.

go.mod, go.sum
This is a backport of #40 to the 1.7 release branch.
=> [release-v1.7] deps: Update modules for v1.7.0.

config.go, version.go, version_buildinfo.go, version_nobuildinfo.go
This reworks the way versions are handled internally to reverse the semantics such that the individual semver components (major, minor, patch, prerelease, and buildmetadata) are parsed from a full string and exported at init time.
Also, since the version is now parsed and verified to be accurate, it updates the pre-release parsing to properly support dots as required by the spec.
Finally, starting with Go version 1.18, it adds the git commit hash to the version string as buildmetadata when no buildmetadata is otherwise specified.
This provides a few main benefits:
- Allows a single linker override to fully specify the version string instead of having separate ones that can only override the prerelease and build metadata portions
- Provides run-time checks to ensure the full version string …
=> version: Support single override and add git hash.

.github/workflows/go.yml, README.md, config.go
This consists of several commit to update the CI and documentation for Go 1.19.  It also takes the opportunity to bump to the latest linter and action versions.
In particular:
- main: Go 1.19 doc comment formatting.
- build: Update to latest action versions.
- `actions/setup-go@84cbf8094393cdc5fe1fe1671ff2647332956b1a #v3.2.1`
- `actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b #v3.0.2`
- build: Update golangci-lint to v1.48.0.
- build: Test against Go 1.19 and remove Go 1.17 accordingly.
- docs: Update README.md for Go 1.19 and rel 1.7.4.
=> multi: Build and doco updates for Go 1.19.

config.go, httpclient.go
As of go 1.16, the "io/ioutil" package is deprecated. All functionality from "io/ioutil" has been moved to either the "io" or "os" packages.
=> multi: Don't use deprecated ioutil package.

.github/workflows/go.yml, README.md
This consists of several commits to update the CI and documentation for Go 1.20. It also takes the opportunity to bump to the latest linter and action versions.
In particular:
- build: Update to latest action versions.
- actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 #v3.5.0
- actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c #v3.3.0
- build: Update golangci-lint to v1.51.1.
- build: Test against Go 1.20 and remove Go 1.18 accordingly.
- docs: Update README.md to required Go 1.19/1.20.
=> multi: Build and doco updates for Go 1.20.

version.go
This clears the PreRelease and sets the BuildMetadata to release.local on the release branch so that anyone building the release branch will end up with version "1.8.0+release.local" indicating it was a local build as opposed to a reproducible release build.
=> [release-v1.8] release: Bump for 1.8.0.

go.mod, go.sum
This updates the module dependencies as follows:
- decred.org/dcrwallet/v3@v3.0.1
- github.com/decred/dcrd/rpc/jsonrpc/types/v4@v4.1.0
Notably, this makes the new `powhash` field of the verbose results of `getblock` and `getblockheader` available.
=> deps: Update to latest modules.

README.md
A suggestion to expand installation docs a bit (based on my recent experience of doing so on Linux).
Rendered version: https://github.com/norwnd/dcrctl/tree/docs-extend-go-install-tutorial
=> docs: Extend go install tutorial.

.github/workflows/go.yml, README.md
This consists of several commits to update the CI and documentation for Go 1.21. It also takes the opportunity to bump to the latest linter and action versions.
In particular:
- build: Update to latest action versions.
- actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # 4.1.0
- actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
- build: Update golangci-lint to v1.54.2
- build: Test against Go 1.21 and remove Go 1.19 accordingly
- docs: Update README.md to required Go 1.20+
=> multi: Build and doco updates for Go 1.21.

version.go
=> [release-v1.8] release: Bump for 1.8.1.

version.go
This clears the `PreRelease` and sets the `BuildMetadata` to `release.local` on the release branch so that anyone building the release branch will end up with version `2.0.0+release.local` indicating it was a local build as opposed to a reproducible release build.
=> [release-v2.0] release: Bump for 2.0.0.

go.mod, go.sum, version.go
This is backports #82 to the 2.0 release branch and bumps the version for 2.0.2.
=> [release-v2.0] multi: Prepare 2.0.2.

go.mod, go.sum, version.go
This update the 2.0 release branch to use the latest wallet module (v4.2.0) and bumps the version for 2.0.5.
=> [release-v2.0] multi: Prepare 2.0.5.

.github/workflows/go.yml, .golangci.yml, README.md
This consists of several commits to update the CI and documentation for Go 1.24. It also takes the opportunity to bump to the latest linter and action versions.
In particular:
- build: Update to latest action versions.
- actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 #5.3.0
- actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
- build: Update golangci-lint to v1.64.5
- build: Test against Go 1.24 and remove Go 1.12 accordingly
- docs: Update README.md to required Go 1.23+
=> multi: Build and doco updates for Go 1.24.
